version: '1.0'

# Defining the compose version
services:

 nginx:
  build: ./nginx
  ports:
    - 8687:80
  volumes:
    - static_volume:/app/root
    - media_volume:/app/mediafiles
  depends_on:
    - myproject
  restart: "always"
 redis:
  ports:
   - 6379:6379
  image: redis:alpine

 celery:
  build: ./internalServices
  command: celery -A internalServices worker -l info --concurrency 1 -Q q1
  volumes:
   - "./internalServices:/app"
  env_file:
   - .localenv
  depends_on:
   - redis
   - db

 celerybeat:
  build: ./internalServices
  command: celery -A internalServices beat -l info
  volumes:
   - "./internalServices:/app"
  env_file:
   - .localenv
  depends_on:
   - redis
   - db

 myproject:
  hostname: internalServices
  depends_on:
    - db
  build: ./internalServices
  command: sh -c "gunicorn internalServices.wsgi:application --bind 0.0.0.0:8000"
  expose: 
   - 8000
  restart: "always"
  env_file:
   - .localenv
  volumes:
   - "./internalServices:/app"
   - static_volume:/app/root
   - media_volume:/app/mediafiles

 db:
  hostname: db
  image: postgres:15
  volumes:
   - postgres_data:/var/lib/postgresql/data/
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=dbpassword
   - POSTGRES_DB=depdb

volumes:
 static_volume:
 media_volume:
 postgres_data:
