# Generated by Django 5.0.3 on 2024-03-14 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='quoteRequest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.quoterequest'),
            preserve_default=False,
        ),
    ]
