# Generated by Django 5.0.3 on 2024-03-14 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_productlist_quoterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='products',
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineItem', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('unitPrice', models.PositiveIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.product')),
            ],
        ),
        migrations.AddField(
            model_name='productlist',
            name='productLines',
            field=models.ManyToManyField(to='sales.productline'),
        ),
    ]
