# Generated by Django 5.0.3 on 2024-03-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_productlist_products_productline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lineItem',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unitPrice',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(default='prod'),
            preserve_default=False,
        ),
    ]
