# Generated by Django 5.0.3 on 2024-03-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_quoterequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='state',
            field=models.CharField(choices=[('val', 'Validated'), ('nval', 'Not Validated')], default='nval'),
            preserve_default=False,
        ),
    ]
