# Generated by Django 5.0.3 on 2024-03-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_quoterequest_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='csv',
            new_name='excel',
        ),
    ]
