# Generated by Django 5.0.3 on 2024-03-18 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_rename_csv_quoterequest_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='contract',
            field=models.FileField(default='s', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='excel',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['xlsx'], message='Please select a valid excel file')]),
        ),
    ]
