# Generated by Django 5.0.3 on 2024-03-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_quoterequest_contract_alter_quoterequest_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='state',
            field=models.CharField(choices=[('dra', 'Drafted'), ('val', 'Validated'), ('nval', 'Not Validated'), ('app', 'Approved'), ('napp', 'Not Approved')], default='dra', max_length=4),
        ),
    ]
