# Generated by Django 5.0.3 on 2024-03-18 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_quoterequest_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.product'),
        ),
    ]
