# Generated by Django 5.0.3 on 2024-03-19 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_productline_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
