# Generated by Django 5.0.3 on 2024-03-20 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_quoterequest_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='General',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='deliveryAddress',
            field=models.CharField(default='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='deliveryTime',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='projectName',
            field=models.CharField(default='projectname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='quotationReference',
            field=models.CharField(default='reference', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='quotationValidity',
            field=models.CharField(default='valid till some time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='scopeOfWork',
            field=models.CharField(default='good scope of work'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='termsOfPayment',
            field=models.CharField(default='payment termas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='warranty',
            field=models.CharField(default='warranty'),
            preserve_default=False,
        ),
    ]
