# Generated by Django 5.0.3 on 2024-03-20 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_quoterequest_date_quoterequest_general_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='Date',
            new_name='date',
        ),
    ]
