# Generated by Django 5.0.3 on 2024-03-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_quoterequest_contractreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotationReference', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('projectName', models.CharField()),
                ('scopeOfWork', models.CharField()),
                ('quotationValidity', models.CharField()),
                ('deliveryTime', models.CharField()),
                ('deliveryAddress', models.CharField()),
                ('termsOfPayment', models.CharField()),
                ('warranty', models.CharField()),
                ('General', models.CharField()),
                ('contractReference', models.CharField(max_length=50)),
                ('contract', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='General',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='contractReference',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='deliveryAddress',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='deliveryTime',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='projectName',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='quotationReference',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='quotationValidity',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='scopeOfWork',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='termsOfPayment',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='warranty',
        ),
    ]
