# Generated by Django 5.0.3 on 2024-03-20 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_staticdate_remove_quoterequest_general_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaticDate',
            new_name='StaticData',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='static_date',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.staticdata'),
        ),
    ]
