# Generated by Django 5.0.3 on 2024-03-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_rename_staticdate_staticdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='static_date',
            new_name='static_data',
        ),
    ]
