# Generated by Django 5.0.3 on 2024-03-20 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_rename_static_date_quoterequest_static_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='productLines',
        ),
        migrations.AddField(
            model_name='productline',
            name='productList',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.productlist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productlist',
            name='quoteRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productLists', to='sales.quoterequest'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='state',
            field=models.CharField(choices=[('dra', 'Drafted'), ('nsta', 'No static Data'), ('val', 'Validated'), ('nval', 'Not Validated'), ('app', 'Approved'), ('napp', 'Not Approved')], default='dra', max_length=4),
        ),
    ]
