# Generated by Django 5.0.3 on 2024-03-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_remove_productlist_productlines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='deliveryAndInstallation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productline',
            name='productList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productLines', to='sales.productlist'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='state',
            field=models.CharField(choices=[('dra', 'Drafted'), ('quo', 'Quotation'), ('val', 'Validated'), ('app', 'Approved'), ('napp', 'Not Approved')], default='dra', max_length=4),
        ),
    ]
