# Generated by Django 5.0.3 on 2024-03-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_quoterequest_deliveryandinstallation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='productsAdded',
            field=models.BooleanField(default=False),
        ),
    ]
