# Generated by Django 5.0.3 on 2024-03-21 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_quoterequest_productsadded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='optional',
        ),
        migrations.AddField(
            model_name='productline',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productline',
            name='unitPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='quoteRequest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='productLists', to='sales.quoterequest'),
        ),
    ]
