# Generated by Django 5.0.3 on 2024-03-25 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_remove_productlist_optional_productline_optional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='odooRef',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productlist',
            name='quoteRequest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='productList', to='sales.quoterequest'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='priceUnit',
            field=models.CharField(choices=[('SAR', 'Saudi Riyals'), ('USD', 'United States Dollar')], max_length=3),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='General',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='contractReference',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='deliveryAddress',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='deliveryTime',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='projectName',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='quotationReference',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='quotationValidity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='scopeOfWork',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='termsOfPayment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='warranty',
            field=models.TextField(),
        ),
    ]
