# Generated by Django 5.0.3 on 2024-03-25 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_product_odooref_alter_productlist_quoterequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticdata',
            name='General',
            field=models.CharField(default='No data was provided', max_length=100, validators=[django.core.validators.MinLengthValidator(9, 'the field must contain at least 9 characters')]),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='contractReference',
            field=models.CharField(default='No data was provided', max_length=50, validators=[django.core.validators.MinLengthValidator(9, 'the field must contain at least 9 characters')]),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='deliveryAddress',
            field=models.CharField(default='No data was provided', max_length=100, validators=[django.core.validators.MinLengthValidator(9, 'the field must contain at least 9 characters')]),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='deliveryTime',
            field=models.CharField(default='No data was provided', max_length=100, validators=[django.core.validators.MinLengthValidator(9, 'the field must contain at least 9 characters')]),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='projectName',
            field=models.CharField(default='No data was provided', max_length=100, validators=[django.core.validators.MinLengthValidator(9, 'the field must contain at least 9 characters')]),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='quotationValidity',
            field=models.CharField(default='No data was provided', max_length=100, validators=[django.core.validators.MinLengthValidator(9, 'the field must contain at least 9 characters')]),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='scopeOfWork',
            field=models.CharField(default='No data was provided', max_length=100, validators=[django.core.validators.MinLengthValidator(9, 'the field must contain at least 9 characters')]),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='termsOfPayment',
            field=models.CharField(default='No data was provided', max_length=100, validators=[django.core.validators.MinLengthValidator(9, 'the field must contain at least 9 characters')]),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='warranty',
            field=models.CharField(default='No data was provided', max_length=100, validators=[django.core.validators.MinLengthValidator(9, 'the field must contain at least 9 characters')]),
        ),
    ]
