# Generated by Django 5.0.3 on 2024-03-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_alter_staticdata_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='odooRef',
            field=models.TextField(unique=True),
        ),
    ]
