# Generated by Django 5.0.3 on 2024-03-26 09:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_alter_product_odooref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_name', models.CharField(max_length=200)),
                ('latin_name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='General',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'the field must contain at least 5 characters')]),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='contractReference',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5, 'the field must contain at least 5 characters')]),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='deliveryAddress',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'the field must contain at least 5 characters')]),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='deliveryTime',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'the field must contain at least 5 characters')]),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='projectName',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'the field must contain at least 5 characters')]),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='quotationReference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='quotationValidity',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'the field must contain at least 5 characters')]),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='scopeOfWork',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'the field must contain at least 5 characters')]),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='termsOfPayment',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'the field must contain at least 5 characters')]),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='warranty',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'the field must contain at least 5 characters')]),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.company'),
        ),
    ]
