# Generated by Django 5.0.3 on 2024-04-03 09:11

from django.db import migrations

def create_groups(apps, schema_migration):
    User = apps.get_model('users', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    # print(Permission.objects.all())
    for perm in Permission.objects.all():
        print(perm.codename)
    view_quote = Permission.objects.get(codename='view_quoterequest')
    add_quote = Permission.objects.get(codename='add_quoterequest')
    change_quote = Permission.objects.get(codename='change_quoterequest')
    delete_quote = Permission.objects.get(codename='delete_quoterequest')
    validate_quote = Permission.objects.get(codename='can_validate_quote')
    add_static_data = Permission.objects.get(codename='can_add_static_to_quote')
    draften_quote = Permission.objects.get(codename='can_draften_quote')
    approve_quote = Permission.objects.get(codename='can_approve_quote')
    disapprove_quote = Permission.objects.get(codename='can_disapprove_quote')
    review_quote = Permission.objects.get(codename='can_review_quote')
    dir_permissions = [
        view_quote,
        approve_quote,
        disapprove_quote
    ]
    sman_permissions = [
        view_quote,
        add_quote,
        change_quote,
        delete_quote,
        validate_quote,
        add_static_data,
        draften_quote,
        review_quote
    ]

    salesmen = Group.objects.get_or_create(name='salesmen')[0]

    dirs = Group.objects.get_or_create(name='salesdirectors')[0]
    dirs.save()
    salesmen.save()
    dirs.permissions.set(dir_permissions)
    salesmen.permissions.set(sman_permissions)
    # subscribers = Group(name='subscribers')
    # subscribers.save()
    # subscribers.permissions.add(view_photo)

    for user in User.objects.all():
        if user.sysRole == 'sdir':
            dirs.user_set.add(user)
        elif user.sysRole == 'sman':
            salesmen.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240402_1034'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
