# Generated by Django 5.0.3 on 2024-04-08 10:58

from django.db import migrations
from sales.models import Serial
from django.db import transaction

def getNextSerial(serial:Serial):
    tmp = serial.next
    serial.next += 1
    serial.save()
    return serial.prefix + str(tmp) +  serial.postfix

@transaction.atomic()
def createSerialz(apps, schema_migration):
    Serials = apps.get_model("sales", "Serial")
    QuoteReq = apps.get_model("sales", "QuoteRequest")
    quotes = QuoteReq.objects.all().order_by("date_created")
    ##if here
    for quote in quotes:
            qsSerial:Serial = Serials.objects.get_or_create(prefix = "quo-", postfix="/2023")[0]
            quote.serial = getNextSerial(qsSerial)
            quote.save()
class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_auto_20240408_1056'),
    ]

    operations = [
        migrations.RunPython(createSerialz)
    ]
